baseURL = 'https://www.kristjan.io/'
languageCode = 'en-us'
title = 'Kristján Ævarsson'

theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog"
url = "/gallery"
weight = 2

[params]
title = "Kristján Ævarsson"
description = "Upplýsingar og verkefni"
favicon = "/favicon-16x16.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Kristján Ævarsson"
  disableSearch = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hæ, ég heiti"
  title = "Kristján"
  subtitle = "Fyrirsögn hér"
  content = "Intro texti hér"
  image = "/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "CV"
    url = "#about"
    download = false
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/kristjan-aevarsson"

  [params.about]
  enable = true
  title = "Um mig"
  image = "/images/me.png"
  content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.experience]
  enable = true
  title = "Reynsla"

    [[params.experience.items]]
    job = "Senior Software Developer"
    company = "Stefna"
    companyUrl = "https://www.stefna.is"
    date = "2006 - present"
    content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      [params.experience.items.featuredLink]
      enable = true
      name = "Verkefnin"
      url = "https://www.stefna.is/is/verkefnin"

    [[params.experience.items]]
    job = "Verslunarstjóri"
    company = "Bónus"
    companyUrl = "https://www.bonus.is"
    date = "1997 - 2003"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.featuredLink]
      enable = false
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software developer for more than one year in Amazon."

    [[params.experience.items]]
    job = "Stefna"
    company = "Stjórn"
    companyUrl = "https://www.stefna.is"
    date = "Jan 2020 - Aug 2020"
    content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

      [params.experience.items.info]
      enable = false

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"


  [params.education]
  enable = true
  index = false
  title = "Menntun"

    [[params.education.items]]
    title = "Master's degree, Leadership and Management"
    date = "2020 - 2022"
    content = """
With major in Project Management.
  """

      [params.education.items.school]
      name = "Háskólinn á Bifrost"
      url = "https://www.bifrost.is"

    [[params.education.items]]
    title = "B.Sc, Computer Science"
    date = "2003 - 2006"
    content = """
  """

      [params.education.items.school]
      name = "Háskólinn á Akureyri"
      url = "https://www.unak.is"

      [params.education.items.featuredLink]
      enable = true
      name = "SKemman"
      url = "https://skemman.is/handle/1946/1181"


  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = false
  title = "Verkefni"

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  title = "Hafa samband"
  content = "Alltaf gaman að heyra í ykkur. Hvort sem það er spurning, hugmyndi eða bara segja halló. Geri mitt besta að svara!"
  email = "bimmsi@gmail.com"
  btnName = "Sendu mér póst"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Nýlegt"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
linkedin = "https://www.linkedin.com/in/kristjan-aevarsson/"
twitter = "https://twitter.com/bimmi"
instagram = "https://www.instagram.com/kristjan_ae/"
facebook = "https://facebook.com/bimmi"

  [params.listPages]
  disableFeaturedImage = false

